---
- name: Install python-pip
  tags: common
  yum: name=python-pip
  become: true

- name: Install docker-py
  tags: common
  pip: name=docker-py version=1.5.0
  become: true

- name: Install rsync
  tags: common
  yum: name=rsync
  become: true

# seems to be a conflict with this and device-mapper. Just showed up 12/15 so it might be bug with a recent yum repo update?
- name: Update lvm2
  tags: common
  yum: name=lvm2 state=latest
  become: true

- name: Install docker
  tags: common
  get_url: dest=/usr/bin/docker url='https://get.docker.com/builds/Linux/x86_64/docker-1.10.3'
  become: true

- name: Set docker permissions
  tags: common
  file: path=/usr/bin/docker mode=0755
  become: true

- name: Setup docker config
  tags: common
  template: src=docker.j2 dest='/etc/sysconfig/docker'
  become: true

- name: Setup docker network config
  tags: common
  copy: src=docker-network dest='/etc/sysconfig/docker-network'
  become: true

- name: Setup docker storage config
  tags: common
  copy: src=docker-storage dest='/etc/sysconfig/docker-storage'
  become: true

- name: Setup docker service file
  tags: common
  copy: src=docker.service dest='/usr/lib/systemd/system/docker.service'
  become: true

- name: Setup docker group
  tags: common
  group: name=docker state=present
  become: true

- name: Setup user docker execution
  tags: common
  user: name="{{ ansible_user_id }}" groups=docker append=yes
  become: true

- name: docker service
  tags: common
  service: name=docker state=started enabled=true
  become: true
